config/routes.rb
Rails.application.routes.draw do

  root 'apuntes#home'

  get 'home' => 'apuntes#home'

  get 'admin' => 'admin#index'

  get 'apuntes/:id' => 'apuntes#show', :as => 'apunte'
  get 'publicacion/:id' => 'apuntes#index', :as => 'apunte_index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    get 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'publicacions/new/:id' => 'publicacions#new', :as => 'new_publicacion'
  get 'publicacions/all' => 'publicacions#all_index', :as => 'all_publicacions'
  resources :publicacions, except: [:new]

  get 'entries/new/:id' => 'entries#new', :as => 'new_entry'
  resources :entries, except: [:new]

  get 'expositors/new/:id' => 'expositors#new', :as => 'new_expositor'
  resources :expositors, except: [:new]

  resources :sections

  get 'SectPub/:id' => 'sections#publicaciones', :as => 'create_publicacion'

  get 'PubEnt/:id' => 'publicacions#entries', :as => 'create_entry'

  get 'PubExp/:id' => 'publicacions#expositors', :as => 'create_expositor'

  get 'contacto' => 'apuntes#contacto'

  get 'about' => 'apuntes#about'

  get 'tutorial' => 'tutoriales#home'
  get 'tutorial/memcached' => 'tutoriales#memcached', :as => 'memcached'
  get 'tutorial/scrum' => 'tutoriales#scrum', :as => 'scrum'
  get 'tutorial/pingesoChecklist' => 'tutoriales#pingesoChecklist', :as => 'pingesoChecklist'

  get 'mejores_apuntes' => 'apuntes#mejores_apuntes'

end

app/models/section.rb
class Section < ActiveRecord::Base
    #attr_accessible :name
	has_many :publicacions

    # Para quitar espacios de los nombres y otros carácteres extraños
    def slug
        direccion = nombre

        direccion = direccion.downcase
        direccion = direccion.gsub("á", "a")
        direccion = direccion.gsub("é", "e")
        direccion = direccion.gsub("í", "i")
        direccion = direccion.gsub("ó", "o")
        direccion = direccion.gsub("ú", "u")
        direccion = direccion.gsub("ñ", "n")
        direccion.delete(' ')
    end

    # Captura el :id del url antes de pasarsela a otros metodos
    def to_param
        "#{id}-#{slug}"
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy, :publicaciones]
  before_action :authenticate_user!  

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /SectPub/:id
  def publicaciones
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:nombre, :sub_nombre)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for @section, :html => {:class => "form-horizontal", "role" => "form"} do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nombre, :class => "form-control" %>
    </div>      
  </div>
  <div class="form-group">
    <%= f.label :sub_nombre, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :sub_nombre, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Actualizar Section", :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/sections/edit.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>Editing Section</h1>
          </div>
        </div>
      </div>
    </section>

	<section id="body" class="officialGrey">
        <div class="container allWhite">
            <br>
			<%= render 'form' %>

			<%= link_to 'Show', @section, :class => "btn btn-warning" %> |
			<%= link_to 'Back', publicacions_path, :class => "btn btn-warning" %>
            <br><br>
		</div>
  	</section>

	<section id="footer" class="officialGrey">
		<div class="container">
		  <div class="panel panel-success">         
		    <div class="panel-heading">
		      <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
		    </div>
		  </div>
		</div>
	</section>

app/views/sections/index.html.erb
    <section id="title">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>Lista de Secciones</h1>
          </div>
        </div>
      </div>
    </section>

    <section id="body">
      <div class="container">
        <div class="table-responsive">

          <%= link_to 'Nueva Sección', new_section_path, :class => "btn btn-link" %>

          <table class="table">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Sub Nombre</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @sections.each do |section| %>
                <tr>
                  <td><%= section.nombre %></td>
                  <td><%= section.sub_nombre %></td>
                  <td><%= link_to 'Show', section, :class => "btn btn-link" %></td>
                  <td><%= link_to 'Edit', edit_section_path(section), :class => "btn btn-link" %></td>
                  <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </section>

    <section id="footer" class="officialGrey">
      <div class="container">
        <div class="panel panel-success">         
          <div class="panel-heading">
            <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
          </div>
        </div>
      </div>
    </section>

app/views/sections/new.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>New section</h1>
          </div>
        </div>
      </div>
    </section>

  	<section id="body" class="officialGrey">
      <div class="container allWhite">
        <br>
        <%= render 'form' %>

  			<%= link_to 'Back', publicacions_path, :class => "btn btn-warning" %>
        <br><br>
  		</div>
    </section>

    <section id="footer" class="officialGrey">
      <div class="container">
        <div class="panel panel-success">         
          <div class="panel-heading">
            <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
          </div>
        </div>
      </div>
    </section>

app/views/sections/publicaciones.html.erb
        <section id="title" class="shinyOrange">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h1><%= @section.nombre %></h1>
                        <p><%= @section.sub_nombre %></p>
                    </div>
                </div>
            </div>
        </section>

        <section id="body" class="officialGrey">
            <div class="container allWhite">

                <%= link_to new_publicacion_path(@section), class: "btn btn-success", "role" => "button" do %>
                  Nueva Publicación <span class="badge"> <%= allPublicaciones.count %></span>
                <% end %>
                <%= link_to entries_path, class: "btn btn-info", "role" => "button" do %>
                  Listar todas las Entradas <span class="badge"> <%= allEntries.count %></span>
                <% end %>
                <%= link_to expositors_path, class: "btn btn-info", "role" => "button" do %>
                  Listar todos los Profesores <span class="badge"> <%= allExpositores.count %></span>
                <% end %>

                <% @section.publicacions.order("id ASC").each do |publicacion| %>
                  <h2>
                    <%= publicacion.nombre %>
                    <small><%= publicacion.siglas %></small>
                    <small><%= publicacion.linkMD %></small>

                    <%= link_to 'Show', publicacion, :class => "btn btn-warning" %>
                    <%= link_to 'Edit', edit_publicacion_path(publicacion), :class => "btn btn-warning" %>
                    <%= link_to 'Destroy', publicacion, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %>
                  </h2>
                  <p>
                    <%= link_to create_expositor_path(publicacion), class: "btn btn-default", "role" => "button" do %>
                      Ver Profesores de esta Publicación <span class="badge"> <%= publicacion.expositors.count %></span>
                    <% end %>
                    <br>
                    <%= link_to create_entry_path(publicacion), class: "btn btn-primary", "role" => "button" do %>
                      Ver Entradas de esta Publicación <span class="badge"> <%= publicacion.entries.count %></span>
                    <% end %>
                  </p>
                <% end %>                          

                <%= link_to 'Back', publicacions_path, :class => "btn btn-warning" %>

                <br><br>
            </div>
        </section>

        <section id="footer" class="officialGrey">
            <div class="container">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
                    </div>
                </div>
            </div>
        </section>

app/views/sections/show.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>
              <strong>Nombre:</strong>
              <%= @section.nombre %>
            </h1>
          </div>
        </div>
      </div>
    </section>

    <section id="body" class="officialGrey">
      <div class="container allWhite">
        <p id="notice"><%= notice %></p>
    		<p>
    		  <strong>Sub Nombre:</strong>
    		  <%= @section.sub_nombre %>
    		</p>

    		<%= link_to 'Edit', edit_section_path(@section), :class => "btn btn-warning" %> |
    		<%= link_to 'Back', publicacions_path, :class => "btn btn-warning" %>
        <br><br>
      </div>
    </section>

    <section id="footer" class="officialGrey">
      <div class="container">
        <div class="panel panel-success">         
          <div class="panel-heading">
            <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
          </div>
        </div>
      </div>
    </section>