config/routes.rb
Rails.application.routes.draw do

  root 'apuntes#home'

  get 'home' => 'apuntes#home'

  get 'admin' => 'admin#index'

  get 'apuntes/:id' => 'apuntes#show', :as => 'apunte'
  get 'publicacion/:id' => 'apuntes#index', :as => 'apunte_index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    get 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'publicacions/new/:id' => 'publicacions#new', :as => 'new_publicacion'
  get 'publicacions/all' => 'publicacions#all_index', :as => 'all_publicacions'
  resources :publicacions, except: [:new]

  get 'entries/new/:id' => 'entries#new', :as => 'new_entry'
  resources :entries, except: [:new]

  get 'expositors/new/:id' => 'expositors#new', :as => 'new_expositor'
  resources :expositors, except: [:new]

  resources :sections

  get 'SectPub/:id' => 'sections#publicaciones', :as => 'create_publicacion'

  get 'PubEnt/:id' => 'publicacions#entries', :as => 'create_entry'

  get 'PubExp/:id' => 'publicacions#expositors', :as => 'create_expositor'

  get 'contacto' => 'apuntes#contacto'

  get 'about' => 'apuntes#about'

  get 'tutorial' => 'tutoriales#home'
  get 'tutorial/memcached' => 'tutoriales#memcached', :as => 'memcached'
  get 'tutorial/scrum' => 'tutoriales#scrum', :as => 'scrum'
  get 'tutorial/pingesoChecklist' => 'tutoriales#pingesoChecklist', :as => 'pingesoChecklist'

  get 'mejores_apuntes' => 'apuntes#mejores_apuntes'

end

app/models/publicacion.rb
class Publicacion < ActiveRecord::Base
	belongs_to :section
	has_many :expositors
	has_many :entries

    # Para quitar espacios de los nombres y otros carácteres extraños
    def slug
        direccion = nombre

        direccion = direccion.downcase
        direccion = direccion.gsub("á", "a")
        direccion = direccion.gsub("é", "e")
        direccion = direccion.gsub("í", "i")
        direccion = direccion.gsub("ó", "o")
        direccion = direccion.gsub("ú", "u")
        direccion = direccion.gsub("ñ", "n")
        direccion.delete(' ')
    end

    # Captura el :id del url antes de pasarsela a otros metodos
    def to_param
        "#{id}-#{slug}"
    end
end

app/controllers/publicacions_controller.rb
class PublicacionsController < ApplicationController
  before_action :set_publicacion, only: [:show, :edit, :update, :destroy, :entries, :expositors]
  before_action :set_new_form, only: [:new]
  before_action :authenticate_user!

  # GET /publicacions
  # GET /publicacions.json
  def index
  end

  def all_index
    @publicacions = Publicacion.all
  end

  # GET /publicacions/1
  # GET /publicacions/1.json
  def show
  end

  # GET /publicacions/new
  def new
    @publicacion = Publicacion.new
    if(!@section.blank?)
      @publicacion.section_id = @section.id
    end
  end

  # GET /publicacions/1/edit
  def edit
  end

  # POST /publicacions
  # POST /publicacions.json
  def create
    @publicacion = Publicacion.new(publicacion_params)

    respond_to do |format|
      if @publicacion.save
        format.html { redirect_to @publicacion, notice: 'Publicacion was successfully created.' }
        format.json { render :show, status: :created, location: @publicacion }
      else
        format.html { render :new }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicacions/1
  # PATCH/PUT /publicacions/1.json
  def update
    respond_to do |format|
      if @publicacion.update(publicacion_params)
        format.html { redirect_to @publicacion, notice: 'Publicacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @publicacion }
      else
        format.html { render :edit }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicacions/1
  # DELETE /publicacions/1.json
  def destroy
    @publicacion.destroy
    respond_to do |format|
      format.html { redirect_to publicacions_url, notice: 'Publicacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /PubEnt/:id
  def entries
  end

  # GET /PubExp/:id
  def expositors
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicacion
      @publicacion = Publicacion.find(params[:id])
    end

    def set_new_form
      if(params[:id] == "blank" || params[:id].to_i < 0)
        @section = nil
      else
        @section = Section.find(params[:id])        
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publicacion_params
      params.require(:publicacion).permit(:nombre, :year, :semestre, :section_id, :linkMD, :siglas)
    end
end

app/helpers/publicacions_helper.rb
module PublicacionsHelper
end

app/views/publicacions/_form.html.erb
<%= form_for @publicacion, :html => {:class => "form-horizontal", "role" => "form"} do |f| %>
  <% if @publicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publicacion.errors.count, "error") %> prohibited this publicacion from being saved:</h2>

      <ul>
      <% @publicacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nombre, :class => "form-control" %>
    </div>      
  </div>
  <div class="form-group">
    <%= f.label :siglas, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :siglas, :class => "form-control" %>
    </div>      
  </div>
  <div class="form-group">
    <%= f.label :year, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :year, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :semestre, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :semestre, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :linkMD, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :linkMD, :class => "form-control" %>
    </div>
  </div>  
  <div class="form-group">
    <%= f.label :section_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <% if @publicacion.section.blank? %>
        <%= f.select :section_id, options_for_select(allSections.map{ |s| [s.nombre, s.id] }), {}, { :class => "form-control" } %>
      <% else %>
        <%= f.select :section_id, options_for_select(allSections.map{ |s| [s.nombre, s.id] }, selected: @publicacion.section.id), {}, { :class => "form-control" } %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Actualizar Publicacion", :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/publicacions/all_index.html.erb
        <section id="title" class="shinyOrange">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h1>Lista de Publicaciones</h1>
                    </div>
                </div>
            </div>
        </section>

        <section id="body" class="officialGrey">
            <div class="container allWhite">
                <h2>Publicaciones:</h2>

                <%= link_to 'New Publicacion', new_publicacion_path("blank"), :class => "btn btn-info" %>

                <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Siglas</th>
                          <th>LinkMD</th>
                          <th>Year</th>
                          <th>Semestre</th>
                          <th>Section</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @publicacions.each do |publicacion| %>
                          <tr>
                            <td><%= publicacion.nombre %></td>
                            <td><%= publicacion.siglas %></td>
                            <td><%= publicacion.linkMD %></td>
                            <td><%= publicacion.year %></td>
                            <td><%= publicacion.semestre %></td>
                            <% if !publicacion.section.blank? %>
                              <td><%= publicacion.section.nombre %></td>
                            <% else %>
                              <td>Sin Section asignada</td>
                            <% end %>
                            <td><%= link_to 'Show', publicacion, :class => "btn btn-warning" %></td>
                            <td><%= link_to 'Edit', edit_publicacion_path(publicacion), :class => "btn btn-warning" %></td>
                            <td><%= link_to 'Destroy', publicacion, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                </div>

                <%= link_to 'Back', publicacions_path, :class => "btn btn-warning" %>

                <br><br>
            </div>
        </section>

        <section id="footer" class="officialGrey">
            <div class="container">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
                    </div>
                </div>
            </div>
        </section>

app/views/publicacions/edit.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>Editing publicacion</h1>
          </div>
        </div>
      </div>
    </section>

	<section id="body" class="officialGrey">
      <div class="container allWhite">
      <br>
			<%= render 'form' %>

			<%= link_to 'Show', @publicacion, :class => "btn btn-warning" %> |
			<%= link_to 'Back', create_publicacion_path(@publicacion.section), :class => "btn btn-warning" %>
      <br><br>
		</div>
  </section>

  <section id="footer" class="officialGrey">
    <div class="container">
      <div class="panel panel-success">         
        <div class="panel-heading">
          <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
        </div>
      </div>
    </div>
  </section>

app/views/publicacions/entries.html.erb
        <section id="title" class="shinyOrange">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h1><%= @publicacion.nombre %></h1>
                        <p>
                            <%= @publicacion.siglas %> - <%= @publicacion.linkMD %>
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section id="body" class="officialGrey">
            <div class="container allWhite">

                <%= link_to new_entry_path(@publicacion), class: "btn btn-success", "role" => "button" do %>
                  Nueva Entrada <span class="badge"> <%= @publicacion.entries.count %></span>
                <% end %>       

                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <th>Fecha</th>
                        <th>Linkmd</th>
                        <th>Publicacion</th>
                        <th>Entry Anterior</th>
                        <th>Entry Siguiente</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @publicacion.entries.order("id ASC").each do |entry| %>
                        <tr>
                          <td><%= entry.nombre %></td>
                          <td><%= entry.fecha %></td>
                          <td><%= entry.linkMD %></td>
                          <td>
                            <% if !entry.publicacion.blank? %>
                              <%= entry.publicacion.nombre %>
                            <% else %>
                              Sin publicación asignada.
                            <% end %>
                          </td>
                          <td>
                            <% if !entry.entry_anterior.blank? %>
                              <%= entry.entry_anterior.nombre %>
                            <% else %>
                              Sin entry anterior asignada.
                            <% end %>
                          </td>
                          <td>
                            <% if !entry.entry_siguiente.blank? %>
                              <%= entry.entry_siguiente.nombre %>
                            <% else %>
                              Sin entry siguiente asignada.
                            <% end %>
                          </td>
                          <td><%= link_to 'Show', entry, :class => "btn btn-warning" %></td>
                          <td><%= link_to 'Edit', edit_entry_path(entry), :class => "btn btn-warning" %></td>
                          <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>                

                <%= link_to 'Back', create_publicacion_path(@publicacion.section), :class => "btn btn-warning" %>

                <br><br>
            </div>
        </section>

        <section id="footer" class="officialGrey">
            <div class="container">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
                    </div>
                </div>
            </div>
        </section>

app/views/publicacions/expositors.html.erb
        <section id="title" class="shinyOrange">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h1><%= @publicacion.nombre %></h1>
                        <p>
                            <%= @publicacion.siglas %> - <%= @publicacion.linkMD %>
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section id="body" class="officialGrey">
            <div class="container allWhite">

                <%= link_to new_expositor_path(@publicacion), class: "btn btn-success", "role" => "button" do %>
                  Nuevo Expositor <span class="badge"> <%= @publicacion.expositors.count %></span>
                <% end %>       

                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <th>Publicacion</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @publicacion.expositors.order("id ASC").each do |expositor| %>
                        <tr>
                          <td><%= expositor.nombre %></td>
                          <td>
                            <% if !expositor.publicacion.blank? %>
                              <%= expositor.publicacion.nombre %>
                            <% else %>
                              No hay publicación asignada.
                            <% end %>
                          </td>
                          <td><%= link_to 'Show', expositor, :class => "btn btn-warning" %></td>
                          <td><%= link_to 'Edit', edit_expositor_path(expositor), :class => "btn btn-warning" %></td>
                          <td><%= link_to 'Destroy', expositor, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>          
                </div>            

                <%= link_to 'Back', create_publicacion_path(@publicacion.section), :class => "btn btn-warning" %>

                <br><br>
            </div>
        </section>

        <section id="footer" class="officialGrey">
            <div class="container">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
                    </div>
                </div>
            </div>
        </section>

app/views/publicacions/index.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>Lista de Secciones</h1>
            <br>
          </div>
        </div>
      </div>
    </section>


    <section id="body" class="officialGrey">
      <div class="container allWhite">

        <%= link_to new_section_path, class: "btn btn-success", "role" => "button" do %>
          Nueva Sección <span class="badge"> <%= allSections.count %></span> 
        <% end %>
        <%= link_to all_publicacions_path, class: "btn btn-info", "role" => "button" do %>
          Listar todas las Publicaciones <span class="badge"> <%= allPublicaciones.count %></span>
        <% end %>
      
        <% for secciones in allSections.order("id ASC") %>
          <h2>
            <%= secciones.nombre %>
            <small><%= secciones.sub_nombre %></small>

            <%= link_to 'Show', secciones, :class => "btn btn-warning" %>
            <%= link_to 'Edit', edit_section_path(secciones), :class => "btn btn-warning" %>
            <%= link_to 'Destroy', secciones, method: :delete, data: { confirm: 'Borrar una sección no borra las publicaciones' }, :class => "btn btn-warning" %>
          </h2>
          <p>
            <%= link_to create_publicacion_path(secciones), class: "btn btn-primary", "role" => "button" do %>
              Ver Publicaciones para esta Sección <span class="badge"> <%= secciones.publicacions.count %></span>
            <% end %>
          </p>
        <% end %>
        <br>
      </div>
    </section>


    <section id="footer" class="officialGrey">
        <div class="container">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
                </div>
            </div>
        </div>
    </section>

app/views/publicacions/new.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>New publicacion</h1>
          </div>
        </div>
      </div>
    </section>

	<section id="body" class="officialGrey">
    <div class="container allWhite">
      <br>
			<%= render 'form' %>

      <% if !@section.blank? %>
        <%= link_to 'Back', create_publicacion_path(@section), :class => "btn btn-warning" %>
      <% else %>
        <%= link_to 'Back', publicacions_path, :class => "btn btn-warning" %>
      <% end %>
      <br><br>
		</div>
  </section>

  <section id="footer" class="officialGrey">
    <div class="container">
      <div class="panel panel-success">         
        <div class="panel-heading">
          <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
        </div>
      </div>
    </div>
  </section>		

app/views/publicacions/show.html.erb
    <section id="title" class="shinyOrange">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h1>
              <strong>Nombre:</strong>
              <%= @publicacion.nombre %>
            </h1>
          </div>
        </div>
      </div>
    </section>


    <section id="body" class="officialGrey">
      <div class="container allWhite">
        <p id="notice"><%= notice %></p>
        <p>
          <strong>Siglas:</strong>
          <%= @publicacion.siglas %>
        </p>

        <p>
          <strong>LinkMD:</strong>
          <%= @publicacion.linkMD %>
        </p>

        <p>
          <strong>Year:</strong>
          <%= @publicacion.year %>
        </p>

        <p>
          <strong>Semestre:</strong>
          <%= @publicacion.semestre %>
        </p>

        <p>
          <strong>Section:</strong>
          <% if !@publicacion.section.blank? %>
          	<%= @publicacion.section.nombre %>
          <% else %>
          	Sin Section asignada
          <% end %>
        </p>    

        <%= link_to 'Edit', edit_publicacion_path(@publicacion), :class => "btn btn-warning" %> |
        <%= link_to 'Back', create_publicacion_path(@publicacion.section), :class => "btn btn-warning" %>
        <br><br>
      </div>
    </section>

    <section id="footer" class="officialGrey">
      <div class="container">
        <div class="panel panel-success">         
          <div class="panel-heading">
            <h3 class="panel-title" align="center"> Desarrollado por Esteban Gaete Flores </h3>
          </div>
        </div>
      </div>
    </section>