config/routes.rb
Rails.application.routes.draw do

  root 'apuntes#home'

  get 'home' => 'apuntes#home'

  get 'admin' => 'admin#index'

  get 'apuntes/:id' => 'apuntes#show', :as => 'apunte'
  get 'publicacion/:id' => 'apuntes#index', :as => 'apunte_index'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    get 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'publicacions/new/:id' => 'publicacions#new', :as => 'new_publicacion'
  get 'publicacions/all' => 'publicacions#all_index', :as => 'all_publicacions'
  resources :publicacions, except: [:new]

  get 'entries/new/:id' => 'entries#new', :as => 'new_entry'
  resources :entries, except: [:new]

  get 'expositors/new/:id' => 'expositors#new', :as => 'new_expositor'
  resources :expositors, except: [:new]

  resources :sections

  get 'SectPub/:id' => 'sections#publicaciones', :as => 'create_publicacion'

  get 'PubEnt/:id' => 'publicacions#entries', :as => 'create_entry'

  get 'PubExp/:id' => 'publicacions#expositors', :as => 'create_expositor'

  get 'contacto' => 'apuntes#contacto'

  get 'about' => 'apuntes#about'

  get 'tutorial' => 'tutoriales#home'
  get 'tutorial/memcached' => 'tutoriales#memcached', :as => 'memcached'
  get 'tutorial/scrum' => 'tutoriales#scrum', :as => 'scrum'
  get 'tutorial/pingesoChecklist' => 'tutoriales#pingesoChecklist', :as => 'pingesoChecklist'

  get 'mejores_apuntes' => 'apuntes#mejores_apuntes'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
	<head>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <meta name="description" content="Apuntes universitarios de Universidad de Santiago de Chile USACH">
	  <meta name="author" content="Esteban Gaete Flores">
        <% if controller_name == "apuntes" %>
            <% if action_name == "home" %>
                <meta property="og:title" content="ApuntesUsach" />
            <% elsif action_name == "show" %>
                <meta property="og:title" content="AU - <%= @publicacion.siglas %>:<%= @entry.nombre %>" />
            <% elsif action_name == "index" %>
                <meta property="og:title" content="AU - <%= @publicacion.nombre %>" />
            <% elsif action_name == "mejores_apuntes" %>
                <meta property="og:title" content="AU - Mejores Apuntes" />
            <% end %>
        <% elsif action_name == "scrum" %>
            <meta property="og:title" content="AU - Metodología Ágil: Scrum" />
        <% elsif action_name == "memcached" %>
            <meta property="og:title" content="AU - Memcached en Ruby on Rails" />
        <% elsif action_name == "pingesoChecklist" %>
            <meta property="og:title" content="AU - PINGESO Checklist" />
        <% elsif action_name == "contacto" %>
            <meta property="og:title" content="AU - Contacto" />
        <% elsif controller_name == "tutoriales" and action_name == "home" %>
            <meta property="og:title" content="AU - Tutoriales" />
        <%else %>
            <meta property="og:title" content="ApuntesUsach" />
        <% end %>
      <meta property="og:site_name" content="ApuntesUsach" />
      <meta property="og:url" content="<%= "http://#{request.host+request.fullpath}" %>" />
      <meta property="og:description" content="Apuntes de Ingeniería Civil Informática ~ ¡De la clase al cuaderno, del cuaderno a internet!"/>
      <meta property="og:image" content="http://apuntesusach.herokuapp.com/assets/estilo/facebookEmbed-1bc16a5cbcbbbbde1c7a99eb68c677c0.png"/>
      <meta property="fb:app_id" content="623051041131579" />
      <meta property="og:type" content="website" />
      <meta property="og:locale" content="es_LA" />
	  <title>Apuntes USACH</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

	  <!-- Google Analytics -->
	  <script>
	    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	    ga('create', 'UA-54468477-1', 'auto');
	    ga('send', 'pageview');

	  </script>

      <!-- Google + -->
      <script src="https://apis.google.com/js/platform.js" async defer>
        {lang: 'es'}
      </script>
	</head>

	<body data-no-turbolink>

        <!-- Script SDK de facebook -->
        <div id="fb-root"></div>
        <script>
          window.fbAsyncInit = function() {
            FB.init({
              appId      : '623051041131579',
              xfbml      : true,
              version    : 'v2.1',
              status     : true
            });
          };

          (function(d, s, id){
             var js, fjs = d.getElementsByTagName(s)[0];
             if (d.getElementById(id)) return;
             js = d.createElement(s); js.id = id;
             js.src = "//connect.facebook.net/es_LA/all.js";
             fjs.parentNode.insertBefore(js, fjs);
           }(document, 'script', 'facebook-jssdk'));
        </script>

        <!-- Header -->
        <nav class="navbar navbar-default navbar-fixed-top strongBlue" role="navigation">
            <div class="container-fluid">


                <div class="navbar-header">
                    <button type="button" class="navbar-toggle softBlue" data-toggle="collapse" data-target="#nav-menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to "Apuntes USACH", home_path, :class => 'navbar-brand softBlue' %>
                </div>

                <div id="nav-menu" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Mejores Apuntes -->
                        <li><%= link_to "Mejores Apuntes", mejores_apuntes_path %></li>

                        <!-- Apuntes -->
                        <% if !allSections.blank? %>
                            <% for auxSection in allSections.order("id ASC") %>
                                <% if !auxSection.publicacions.blank? %>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <%= auxSection.nombre %> <span class="glyphicon glyphicon-chevron-down"></span> 
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><%= auxSection.sub_nombre %></li>
                                            <li class="divider"></li>
                                            <% for publicaciones in auxSection.publicacions.order("id ASC") %>                                          
                                                <% if !publicaciones.entries.blank? %>
                                                    <li>
                                                        <%= link_to apunte_index_path(publicaciones) do %>
                                                            <%= publicaciones.nombre %> <span class="glyphicon glyphicon-chevron-right"></span>
                                                        <% end %>
                                                        <div class="hidden-xs">
                                                            <ul class="dropdown-menu sub-menu">
                                                                <li><%= link_to publicaciones.nombre, apunte_index_path(publicaciones) %></li>
                                                                <li class="divider"></li>
                                                                <% for entrada in publicaciones.entries.order("id ASC") %>
                                                                    <li><%= link_to entrada.nombre, apunte_path(entrada) %></li>
                                                                <% end %>
                                                            </ul>
                                                        </div>
                                                    </li>
                                                <% else %>
                                                    <li><%= link_to publicaciones.nombre, apunte_index_path(publicaciones) %></li>
                                                <% end %>                                           
                                            <% end %>
                                        </ul>
                                    </li>
                                <% else %>
                                    <li><a href="#"><%= auxSection.nombre %></a></li>
                                <% end %>                       
                            <% end %>
                        <% end %>

                        <!-- Tutorial -->
                        <li class="dropdown">
                            <%= link_to tutorial_path do %>
                                Tutoriales <span class="glyphicon glyphicon-chevron-down"></span>
                            <% end %>
                            <ul class="dropdown-menu" role="menu">
                                <li>Mediiic!!!!</li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Metodología Ágil: Scrum", scrum_path %>
                                </li>
                                <li>
                                    <%= link_to "Memcached en Ruby on Rails", memcached_path %>
                                </li>
                                <li>
                                    <%= link_to "Guía para Presentaciones en PINGESO", pingesoChecklist_path %>
                                </li>
                            </ul>
                        </li>

                        <!-- Sobre AU -->
                        <li><%= link_to "Sobre AU", about_path %></li>

                        <!-- Contacto -->
                        <li><%= link_to "Contacto", contacto_path %></li>
                    </ul>
                </div>


            </div>
        </nav> <!-- Header -->

		<!-- administración -->
		<% if user_signed_in? %>
			<section id="header" class="hidden-print softBlue">
				<div class="container">
					<p class="notice pull-left"><%= notice %></p>
					<p class="alert pull-left"><%= alert %></p>

					<%= link_to  "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-danger pull-right", "role" => "button" %>
					<%= link_to  "Administración", admin_path, class: "btn btn-success pull-right", "role" => "button" %>
				</div>
			</section>
		<% end %>

		<%= yield %>

        <h2 class="visible-print-block">Desarrollado por Esteban Gaete Flores</h2>

        <!-- Script para ver codigos fuentes con colores -->
        <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

	</body>
</html>